### PR TITLE
"Symbol not found: _clock_gettime" error on the runtime fixed on OS X prior to 10.12 when Netty is compiled on OS X 10.12

### PR DESCRIPTION
**Pull request by tejksat**
`mach_approximate_time()` and `mach_absolute_time()` functions must be used at the compile time because `clock_gettime()` is not supported on OS X prior to 10.12 and Netty must not be compiled using it even on OS X 10.12.

### CODE REVIEW

**Comment by Scottmitch** [comment]
@tejksat - Can you clarify what the issue is? The last commit doesn't make sense to me. Also please comment on https://github.com/netty/netty/pull/6000.

**Comment by tejksat** [comment]
@Scottmitch I agree that this looks weird from the first glance. But there is actually a problem. How to reproduce it:
- `maven install` for Netty project on OS X 10.12
- try using this version of Netty with UNIX domain socket on OS X 10.11 or older and you get `Symbol not found: _clock_gettime` exception:
```
...
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.unix.DomainSocketAddress;
...

    Bootstrap bootstrap = new Bootstrap();
    bootstrap.connect(new DomainSocketAddress("/var/run/docker.sock")).sync().channel();
...
```

I will try to explain what leads to the problem. The problem is in a condition that is used in `netty_unix_util.h`: `#if defined(__MACH__) && !defined(CLOCK_REALTIME)`. On OS X 10.12 `CLOCK_REALTIME` macros **does** present, so `NETTY_USE_MACH_INSTEAD_OF_CLOCK` is not defined and therefore the method `netty_unix_util_clock_gettime()` located in `netty_unix_util.c` uses `clock_gettime()` system function. And this system method is **not** available for OS X 10.11 and older what leads to run-time error on older versions of OS X.

**Comment by Scottmitch** [comment]
Thanks for clarifying. Building on macOS 10.12 and trying to use the artifact on older releases was all I needed to know. Your commit always uses the old `mach_` interfaces, which is not what we want. We want to use the standard `clock_gettime` interface when available. If we wanted to support using the same artifacts built on 10.12+ on older macOS we could use weak linking. However I'm not convinced we want/need to do this. This will introduce additional conditionals in the `netty_unix_util_clock_gettime` path which is expected to be fast and called frequently. This code is also currently common between linux/macOS, and that means this change would also impact linux or require a separate method for the two platforms which introduces complexity. Please update to the latest version of macOS, or build your own artifacts on older versions of macOS.

**Comment by tejksat** [comment]
@Scottmitch I understand your point of view.
> Please update to the latest version of macOS, or build your own artifacts on older versions of macOS.

I believe if Netty library release, that is going to be put in Maven Central or JPoint, will be built with macOS 10.12 these words are going to be told a lot of times. When this feature will be available developers that uses Netty won't be expecting incompatibility between OS X versions and this would consequently affect their users. If you take a look at the OS X versions market share statistics there are many people who uses OS X 10.11, 10.10 and even older versions (see f.e. https://www.netmarketshare.com/operating-system-market-share.aspx).

`docker-java` library, which uses Netty, could be taken as an example. Now the the only standard and painless way for connecting to Docker for Mac is via `unix:///var/run/docker.sock` UNIX socket. To use your long-waited feature `docker-java` library maintainers or developers that uses their library would be forced to built their own Netty Mac-dependent artifact that would work on any OS X version. It is fine and quite easy but if this wonderful feature is for users of Netty why not to make it work out-of-the box for all of them?..

**Comment by stevenschlansker** [comment]
This is quite frustrating -- a developer brought in `testcontainers`, which brings in `netty`, which exposes this issue and he broke the build on some of our developers' machines.  We're now forced to choose between upgrading our *hardware* or using Netty...

I will echo the request that publishing an artifact to Maven Central which does not work on ~ 1/3 the Mac install base (roughly guessing based on the link above) is not very nice, and "just build your own" isn't really a solution when you bring in a third party project that depends on Netty.

**Pull request closed without merging**
